jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - name: Prepare actions
        uses: ./.github/actions/prepare
      - name: Sync Astro
        run: bun astro sync
      - name: Typecheck
        run: bun lint
      - uses: mshick/add-pr-comment@v2
        if: failure()
        with:
          message-failure: |
            Uh oh! ESLint found some issues. Please run `bun lint:fix` and commit the changes

name: Lint Check

on:
  pull_request: ~
  merge_group: ~

  push:
    branches:
      - main
