jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - name: Prepare actions
        uses: ./.github/actions/prepare
      - name: Sync Astro
        run: bun astro sync
      - name: Prettier
        run: bun fmt:check
      - uses: mshick/add-pr-comment@v2
        if: failure()
        with:
          message-failure: |
            Uh oh! Prettier found some issues. Please run `bun fmt` to fix it

name: Prettier Check

on:
  pull_request: ~
  merge_group: ~

  push:
    branches:
      - main
